version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./web:/usr/local/app
    env_file: .env

  db:
    image: postgres:15.3-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file: .env
