require: rubocop-rails

AllCops:
  NewCops: enable
  Include:
    - 'app/**/*.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/SymbolArray:
  EnforcedStyle: brackets

Rails/SkipsModelValidations:
  Exclude:
    # в данном случае оправдано т.к.:
    # - валидировать нечего, значения передаются
    #   из других моделей, где проходят валидацию
    # - inser_all! работает кратно быстрее чем create,
    #   иначе создание тысяч записей будет крайне медленным
    - 'app/interactors/create_distributed_options_for_device.rb'

Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*rb'
